<a href="https://colab.research.google.com/github/Bokenasubi-T/pomacea-distribution-jp/blob/main/notebooks/08_convert_landuse_to_grid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#08_Convert Land-use data into raster data
Link the land-use data to 30-sec grids and save it as raster data.

*   Input : landuse_100m_2021.parquet
*   Output item : ***

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Project folders on Google Drive
BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/pomacea"
DATA_DIR = f"{BASE_DIR}/data"

Mounted at /content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
# read land-use data(parquet file)
landuse_100m_2021 = pd.read_parquet(f"{DATA_DIR}/landuse_100m_2021.parquet")
# check data
landuse_100m_2021.head(5)

     L03b_001 L03b_002
0  3622572688     0600
1  3622572689     0600
2  3622572692     0600
3  3622572696     0600
4  3622572697     0600

In [18]:
# calculate coordinate of the centre of mesh
# tear apart mesh-code for calculation
meshcode12 = landuse_100m_2021["L03b_001"] // 10**8
meshcode34 = (landuse_100m_2021["L03b_001"] // 10**6) % 100
meshcode5 = (landuse_100m_2021["L03b_001"] // 10**5) % 10
meshcode6 = (landuse_100m_2021["L03b_001"] // 10**4) % 10
meshcode7 = (landuse_100m_2021["L03b_001"] // 10**3) % 10
meshcode8 = (landuse_100m_2021["L03b_001"] // 10**2) % 10
meshcode9 = (landuse_100m_2021["L03b_001"] // 10) % 10
meshcode10 = landuse_100m_2021["L03b_001"] % 10

# calculate coordinate of the centre of mesh
landuse_100m_2021["lat"] = meshcode12 / 1.5 + meshcode5 * 5/60 + meshcode7 * 30/3600 + meshcode9 * 3/3600 + 1.5/3600
landuse_100m_2021["lon"] = meshcode34 +100 + meshcode6 * 7.5/60 + meshcode8 * 45/3600 + meshcode10 * 4.5/3600 + 2.25/3600

# delete variables for calculating coordinate since it require memory space a lot
del meshcode12, meshcode34, meshcode5, meshcode6, meshcode7, meshcode8, meshcode9, meshcode10

# check data
landuse_100m_2021.head(5)

     L03b_001 L03b_002        lat         lon
0  3622572688     0600  24.440417  122.960625
1  3622572689     0600  24.440417  122.961875
2  3622572692     0600  24.441250  122.953125
3  3622572696     0600  24.441250  122.958125
4  3622572697     0600  24.441250  122.959375